export type SupportContext={name:string;role:string;ibStatus:string;ibApplication:string;telegramLinked:boolean;discordLinked:boolean;hasTelegramInvite:boolean;hasDiscordInvite:boolean};
type Entry={id:string;keywords:string;answer:string};

const BUILT_IN:Entry[]=[
  {id:'welcome',keywords:'hello hi hey help support what can you do assistant chatbot',answer:'Hello {{name}}. I can help with registration, login, profiles, Elite applications, approved brokers, Telegram and Discord verification, memberships, Ziina payments, courses, events, the Elite Vault, live signals, performance, security, and administrator support.'},
  {id:'register',keywords:'register registration create sign up signup new user database error account',answer:'Create an account from the site registration form using a valid email and password. After registration, sign in to the Members Portal. If the email is already registered, use that account instead of creating another one.'},
  {id:'login',keywords:'login log in sign in cannot access portal authentication session',answer:'Sign in from the Members Portal using your registered email and password. If the page still appears signed out, sign out completely, refresh the browser, and sign in again.'},
  {id:'logout',keywords:'logout log out sign out admin session security shared computer',answer:'Use Sign Out in the portal sidebar. The session is cleared and protected portal or admin pages will require authentication again. Always sign out on a shared device.'},
  {id:'password',keywords:'password forgot reset recover change password',answer:'Use the password-recovery option on the sign-in screen when available. Never send a password, one-time code, API key, or bot token through support chat.'},
  {id:'profile',keywords:'profile name avatar photo picture email account details update',answer:'Open Profile in the Members Portal to update supported account information and your avatar. Email or identity changes that require verification should be escalated through Contact Admin.'},
  {id:'membership',keywords:'membership package premium elite plan upgrade access price pricing benefits',answer:'Open Packages to compare active membership plans, benefits, and payment options. Approved Elite members receive full website access while their Elite status remains active.'},
  {id:'ziina',keywords:'ziina payment pay checkout link transaction pending failed receipt',answer:'Membership payment links are shown under Packages and are managed by the administrator. If payment completed but access is not active, open a support ticket and include the transaction reference—never card or banking credentials.'},
  {id:'refund',keywords:'refund cancel payment charge dispute money back',answer:'Refunds and payment disputes require administrator review. Use Contact Admin and provide the package or purchase name plus the transaction reference.'},
  {id:'ib_apply',keywords:'ib introducing broker apply application register broker account number referral',answer:'Open Elite Access, choose an administrator-approved broker, create the broker account through its displayed referral link, then submit the broker name and account number for review.'},
  {id:'ib_status',keywords:'ib status application pending approved rejected approval how long review 24 48',answer:'Your Elite profile status is {{ib_status}} and your latest application is {{ib_application}}. Reviews normally follow the timeframe displayed on the application confirmation. The assistant cannot approve an application; an administrator must verify it.'},
  {id:'ib_broker',keywords:'broker list choose multiple approved minimum deposit referral link manual broker',answer:'The broker dropdown contains only active brokers configured by the administrator. Use the displayed referral link and follow the minimum-deposit information for the selected broker.'},
  {id:'ib_approval',keywords:'after approved grant access elite invitation community button',answer:'After administrator approval, website Elite access becomes active and Telegram/Discord invitation controls appear in Elite Access. Community joining remains optional and can be completed later.'},
  {id:'telegram_verify',keywords:'telegram verify connect link bot number phone identity start code',answer:'In Elite Access, click Verify Telegram and start the bot from the 15-minute one-time link. The system verifies the real Telegram user ID; it does not request or store your phone number.'},
  {id:'telegram_join',keywords:'telegram join channel invitation invite approved expire access',answer:'{{telegram_status}} After Elite approval and Telegram verification, use Join Telegram in Elite Access. The personalized invitation is single-use and has no time expiration.'},
  {id:'telegram_change',keywords:'telegram change replace update different new account number disconnect unlink',answer:'Open Elite Access, click change beside the verified Telegram identity, confirm disconnection, then verify the replacement Telegram account. Your approved website Elite access is not removed.'},
  {id:'discord_verify',keywords:'discord verify connect oauth email identity authorize account',answer:'In Elite Access, click Connect Discord and authorize the official Discord identity screen. The site stores the Discord user ID, display name, a masked email, and a one-way email hash—not the full email or OAuth token.'},
  {id:'discord_join',keywords:'discord join server invitation invite approved membership screening',answer:'{{discord_status}} After Elite approval and Discord verification, click Join Discord in Elite Access. Discord may ask you to complete server Membership Screening if the administrator enabled it.'},
  {id:'discord_change',keywords:'discord change replace update different email account disconnect unlink',answer:'Open Elite Access, click change beside the verified Discord identity, disconnect it, then complete Discord authorization using the replacement account.'},
  {id:'community_manual',keywords:'admin approve telegram discord manually channel server join request',answer:'The website invitation itself does not require another MAHustler approval. Telegram requires the bot to have invite permission. Discord may require its own Membership Screening, depending on server settings.'},
  {id:'courses',keywords:'course academy lesson enroll enrollment access marketplace watch learn free ib benefit',answer:'Open My Courses to see active enrollments and available academy courses. Members with approved Elite access can enroll in every offered course for free. Members without approved Elite access pay the displayed course price or can apply an eligible coupon.'},
  {id:'vault',keywords:'elite vault repository tools materials files folder download installer resources documents google drive',answer:'Open Elite Vault in the Members Portal to browse official folders, tools, downloads, documents, and external resources published by the administrator. Vault access requires an active membership or approved Elite access. Downloads use secure short-lived links.'},
  {id:'coupon',keywords:'coupon promo discount code course redeem invalid expired',answer:'Enter the coupon during the supported course enrollment flow. Coupons can be limited by date, usage, course, discount type, or status. Contact Admin if a valid issued code is rejected.'},
  {id:'events',keywords:'event webinar seminar register ticket capacity schedule date location',answer:'Open My Events to see registrations and available events. Event availability can depend on capacity, date, membership, payment, or an administrator grant.'},
  {id:'signals',keywords:'signal live active buy sell entry take profit tp stop loss sl risk',answer:'Entitled members see the live active signal on the portal dashboard. Each signal can include direction, entry, take-profit, stop-loss, and analysis notes. Signals are informational and are not personalized financial advice.'},
  {id:'history',keywords:'signal history old previous closed result win loss trade update',answer:'Signal History appears below the live signal for entitled members and includes completed outcomes received from the admin or connected EA/Telegram feed.'},
  {id:'performance',keywords:'performance daily weekly monthly pnl profit loss win rate statistics report',answer:'Daily, weekly, and monthly performance summaries are calculated from completed signal records. Telegram daily summaries also appear in the member event feed when received.'},
  {id:'regime',keywords:'market regime trending ranging accumulation distribution shift quant ai',answer:'The current market regime and regime changes appear in Quant AI and the member signal feed. Regime messages describe the system state; they are not individual trading instructions.'},
  {id:'feed',keywords:'feed alert system online disconnected reconnected halt risk update daily summary',answer:'The portal event feed includes system status, connection alerts, trade updates, risk halts, regime shifts, and performance summaries received from the signal system.'},
  {id:'risk',keywords:'risk warning financial advice loss drawdown halt stop trading safe',answer:'Follow your own risk limits and broker controls. Website signals and performance reports are informational, not financial advice. A daily halt means the signal system has stopped new entries under its configured risk rules.'},
  {id:'notifications',keywords:'notification email telegram discord alert not receiving missing',answer:'Website updates appear in the member portal. Telegram and Discord require the relevant verified account and completed invitation. Browser, Telegram, Discord, or email notification settings may also affect delivery.'},
  {id:'privacy',keywords:'privacy data phone email stored information secure identity',answer:'The community-linking flow avoids storing Telegram phone numbers. Discord stores a platform user ID, display information, masked email, and one-way email hash. Secrets and integration credentials are server-side and are never shown to members.'},
  {id:'security',keywords:'security scam token api key bot password secret phishing safe',answer:'Never share passwords, one-time codes, API keys, bot tokens, payment credentials, or recovery codes. MAHustler support should not request these in chat.'},
  {id:'support',keywords:'human admin agent contact support ticket complaint problem unresolved',answer:'Click Contact Admin in this chat to open a human support ticket. Continue writing in the same conversation; an administrator can reply from the AI Support inbox.'},
  {id:'availability',keywords:'local server vercel deploy offline internet cost api calls free built in provider',answer:'The Built-in Local assistant runs inside this website and makes no model API calls. Future AI providers can be enabled explicitly by an administrator after their server credentials are configured.'},
];

const STOP=new Set('a an and are as at be by can could do does for from how i in is it me my of on or please the this to was what when where which who why will with you your'.split(' '));
const ALIASES:Record<string,string>={signin:'login',signed:'login',logging:'login',signup:'register',registration:'register',registered:'register',tg:'telegram',tele:'telegram',disc:'discord',membership:'package',plans:'package',pricing:'package',payments:'payment',paid:'payment',academy:'course',lessons:'course',webinar:'event',trades:'signal',trading:'signal',pnl:'performance',profits:'performance',losses:'performance',administrator:'admin',human:'support',oauth2:'oauth'};
function tokens(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,' ').split(' ').filter(x=>x.length>1&&!STOP.has(x)).map(x=>ALIASES[x]??x);}
function customEntries(raw:string){
  const result:Entry[]=[];for(const [index,line] of raw.split('\n').entries()){const clean=line.trim();if(!clean||clean.startsWith('#'))continue;const split=clean.includes('|')?clean.indexOf('|'):clean.includes('=>')?clean.indexOf('=>'):-1;if(split<1)continue;const width=clean.slice(split,split+2)=='=>'?2:1;result.push({id:`custom-${index}`,keywords:clean.slice(0,split).trim(),answer:clean.slice(split+width).trim()});}return result.filter(x=>x.answer);
}
function render(answer:string,context:SupportContext){return answer.replaceAll('{{name}}',context.name||'there').replaceAll('{{ib_status}}',context.ibStatus||'none').replaceAll('{{ib_application}}',context.ibApplication||'none').replaceAll('{{telegram_status}}',context.telegramLinked?'Your Telegram identity is verified.':'Your Telegram identity is not linked yet.').replaceAll('{{discord_status}}',context.discordLinked?'Your Discord identity is verified.':'Your Discord identity is not linked yet.');}

export function localKnowledgeAnswer(question:string,context:SupportContext,customKnowledge=''){
  const query=tokens(question),unique=new Set(query),phrase=question.toLowerCase();const entries=[...customEntries(customKnowledge),...BUILT_IN];
  const ranked=entries.map(entry=>{const keys=tokens(entry.keywords),keySet=new Set(keys);let score=0;for(const token of unique)if(keySet.has(token))score+=keys[0]===token?3:2;if(phrase.includes(entry.keywords.toLowerCase()))score+=8;if(entry.id.startsWith('custom-')&&score>0)score+=1;return {entry,score};}).sort((a,b)=>b.score-a.score);
  if((ranked[0]?.score??0)>=2)return render(ranked[0].entry.answer,context);
  return `I could not find a confident answer for that yet. I can help with registration, login, Elite applications, brokers, Telegram, Discord, memberships, Ziina payments, courses, events, signals, performance, privacy, or support tickets. Try rephrasing the question, or click Contact Admin for a human answer.`;
}

export const BUILT_IN_TOPIC_COUNT=BUILT_IN.length;
