'use client';

import {useCallback,useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import Link from 'next/link';
import {BookOpen,Check,CheckCircle2,ChevronLeft,ChevronRight,Circle,Clock,Film,Loader2,LockKeyhole,Menu,X} from 'lucide-react';
import {toast} from 'sonner';
import {authFetch} from '@/lib/utils/authFetch';
import type {LmsCoursePayload,LmsLesson} from '@/types/lms';

export default function CoursePlayer({courseId}:{courseId:string}){
  const [data,setData]=useState<LmsCoursePayload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selectedId,setSelectedId]=useState<string|null>(null),[saving,setSaving]=useState(false),[mobileNav,setMobileNav]=useState(false);
  const lastSavedSecond=useRef(0);
  const load=useCallback(async()=>{setLoading(true);try{const response=await authFetch(`/api/me/courses/${courseId}/lms`),result=await response.json();if(!response.ok)throw new Error(result.error);setData(result);setError('');setSelectedId(current=>current??result.summary.last_lesson_id??result.modules.flatMap((module:{lessons:LmsLesson[]})=>module.lessons)[0]?.id??null);}catch(reason){setError(reason instanceof Error?reason.message:'Could not load this course');}finally{setLoading(false);}},[courseId]);
  useEffect(()=>{void load();},[load]);
  const lessons=useMemo(()=>data?.modules.flatMap(module=>module.lessons)??[],[data]);
  const selected=lessons.find(lesson=>lesson.id===selectedId)??lessons[0]??null,index=selected?lessons.findIndex(lesson=>lesson.id===selected.id):-1;

  async function saveProgress(lesson:LmsLesson,status:'in_progress'|'completed',seconds=0,refresh=false){if(status==='in_progress'&&lesson.progress?.status==='completed')return true;try{const response=await authFetch(`/api/me/courses/${courseId}/progress`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lesson_id:lesson.id,status,progress_seconds:seconds})});if(!response.ok){const result=await response.json().catch(()=>({}));throw new Error(result.error||'Progress update failed');}if(refresh)await load();return true;}catch(reason){if(refresh)toast.error(reason instanceof Error?reason.message:'Progress update failed');return false;}}
  function selectLesson(lesson:LmsLesson){setSelectedId(lesson.id);setMobileNav(false);lastSavedSecond.current=lesson.progress?.progress_seconds??0;void saveProgress(lesson,'in_progress',lesson.progress?.progress_seconds??0);}
  async function complete(){if(!selected||saving)return;setSaving(true);const saved=await saveProgress(selected,'completed',Math.max(lastSavedSecond.current,selected.progress?.progress_seconds??0),true);if(saved)toast.success('Lesson completed');setSaving(false);}
  function videoProgress(seconds:number){if(!selected||selected.progress?.status==='completed'||seconds-lastSavedSecond.current<20)return;lastSavedSecond.current=Math.floor(seconds);void saveProgress(selected,'in_progress',Math.floor(seconds));}

  if(loading&&!data)return <div style={page}><div style={center}><Loader2 size={28} color="#D4AF37" style={{animation:'playerSpin .8s linear infinite'}}/><p style={{fontSize:'.72rem',color:'#666'}}>Loading course…</p></div><style>{`@keyframes playerSpin{to{transform:rotate(360deg)}}`}</style></div>;
  if(error||!data)return <div style={page}><div style={center}><LockKeyhole size={31} color="#D4AF37"/><h1 style={{fontFamily:'Cinzel,serif',fontSize:'1.1rem'}}>Course Access Required</h1><p style={{fontSize:'.72rem',color:'#777',maxWidth:'420px',textAlign:'center',lineHeight:1.6}}>{error||'This course is unavailable.'}</p><Link href="/portal/courses" style={goldLink}>Return to My Courses</Link></div></div>;
  return <div style={page}><style>{`@keyframes playerSpin{to{transform:rotate(360deg)}} @media(max-width:900px){.lms-player-nav{display:none!important}.lms-player-nav.open{display:flex!important;position:fixed!important;inset:72px 0 0 0!important;width:auto!important;z-index:80!important}.lms-player-main{margin-left:0!important}.lms-mobile-toggle{display:grid!important}}`}</style>
    <header style={topHeader}><div style={{minWidth:0}}><Link href="/portal/courses" style={{fontSize:'.6rem',color:'#777',textDecoration:'none'}}>← My Courses</Link><h1 style={{fontFamily:'Cinzel,serif',fontSize:'1rem',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',marginTop:'4px'}}>{data.course.title}</h1></div><div style={{display:'flex',alignItems:'center',gap:'12px'}}><div style={{textAlign:'right'}}><p style={{fontSize:'.56rem',color:'#777'}}>{data.summary.completed} OF {data.summary.total} LESSONS</p><p style={{fontFamily:'Cinzel,serif',fontSize:'.8rem',color:'#D4AF37',marginTop:'2px'}}>{data.summary.percent}% COMPLETE</p></div><button className="lms-mobile-toggle" onClick={()=>setMobileNav(value=>!value)} style={mobileButton}>{mobileNav?<X size={17}/>:<Menu size={17}/>}</button></div></header>
    <div style={{display:'flex',minHeight:'calc(100vh - 154px)'}}>
      <aside className={`lms-player-nav ${mobileNav?'open':''}`} style={sidebar}><div style={{padding:'14px 16px',borderBottom:'1px solid rgba(255,255,255,.05)'}}><div style={progressTrack}><div style={{...progressFill,width:`${data.summary.percent}%`}}/></div></div><div style={{flex:1,overflowY:'auto',padding:'10px'}}>{data.modules.map((module,moduleIndex)=><section key={module.id} style={{marginBottom:'14px'}}><p style={{fontSize:'.53rem',letterSpacing:'2px',color:'#666',padding:'5px 7px'}}>MODULE {moduleIndex+1}</p><h2 style={{fontFamily:'Cinzel,serif',fontSize:'.68rem',padding:'0 7px 7px',lineHeight:1.4}}>{module.title}</h2>{module.lessons.map((lesson,lessonIndex)=>{const active=lesson.id===selected?.id,done=lesson.progress?.status==='completed';return <button key={lesson.id} onClick={()=>selectLesson(lesson)} style={{width:'100%',display:'grid',gridTemplateColumns:'20px minmax(0,1fr) auto',gap:'7px',alignItems:'center',textAlign:'left',padding:'9px 8px',marginBottom:'3px',background:active?'rgba(212,175,55,.09)':'transparent',border:active?'1px solid rgba(212,175,55,.2)':'1px solid transparent',color:active?'#fff':'#888',cursor:'pointer'}}>{done?<CheckCircle2 size={14} color="#34D399"/>:<Circle size={13} color={active?'#D4AF37':'#555'}/>}<span style={{fontSize:'.65rem',lineHeight:1.35}}>{lessonIndex+1}. {lesson.title}</span>{lesson.duration_seconds&&<span style={{fontSize:'.5rem',color:'#555'}}>{Math.ceil(lesson.duration_seconds/60)}m</span>}</button>;})}</section>)}</div></aside>
      <main className="lms-player-main" style={main}>{!selected?<div style={center}><BookOpen size={35} color="#555"/><h2 style={{fontFamily:'Cinzel,serif',fontSize:'1rem'}}>Curriculum Coming Soon</h2><p style={{fontSize:'.7rem',color:'#666'}}>The administrator has not published any lessons yet.</p></div>:<article style={{maxWidth:'980px',margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',gap:'12px',alignItems:'flex-start',marginBottom:'16px'}}><div><p style={{fontSize:'.55rem',letterSpacing:'2.5px',color:'#D4AF37'}}>LESSON {index+1} OF {lessons.length}</p><h2 style={{fontFamily:'Cinzel,serif',fontSize:'1.45rem',marginTop:'7px',lineHeight:1.25}}>{selected.title}</h2>{selected.duration_seconds&&<p style={{display:'flex',alignItems:'center',gap:'5px',fontSize:'.62rem',color:'#666',marginTop:'7px'}}><Clock size={12}/>{Math.ceil(selected.duration_seconds/60)} minutes</p>}</div>{selected.progress?.status==='completed'&&<span style={completeBadge}><Check size={12}/> Completed</span>}</div><VideoStage lesson={selected} onProgress={videoProgress}/><div style={contentPanel}>{selected.content?<p style={{whiteSpace:'pre-wrap',fontSize:'.8rem',lineHeight:1.85,color:'#C5C5C5'}}>{selected.content}</p>:<div style={{textAlign:'center',padding:'35px',color:'#555'}}><BookOpen size={24}/><p style={{fontSize:'.68rem',marginTop:'9px'}}>Lesson notes will appear here.</p></div>}</div><footer style={{display:'flex',justifyContent:'space-between',gap:'10px',alignItems:'center',paddingTop:'16px',borderTop:'1px solid rgba(255,255,255,.06)',flexWrap:'wrap'}}><button disabled={index<=0} onClick={()=>index>0&&selectLesson(lessons[index-1])} style={{...navButton,opacity:index<=0 ? .35 : 1}}><ChevronLeft size={14}/> Previous</button><button onClick={()=>void complete()} disabled={saving||selected.progress?.status==='completed'} style={{...completeButton,opacity:saving||selected.progress?.status==='completed' ? .5 : 1}}>{saving?<Loader2 size={14}/>:<Check size={14}/>} {selected.progress?.status==='completed'?'Completed':'Mark Complete'}</button><button disabled={index>=lessons.length-1} onClick={()=>index<lessons.length-1&&selectLesson(lessons[index+1])} style={{...navButton,opacity:index>=lessons.length-1 ? .35 : 1}}>Next <ChevronRight size={14}/></button></footer></article>}</main>
    </div>
  </div>;
}

function VideoStage({lesson,onProgress}:{lesson:LmsLesson;onProgress:(seconds:number)=>void}){if(!lesson.playback_url)return <div style={videoPlaceholder}><Film size={38} color="#555"/><p style={{fontFamily:'Cinzel,serif',fontSize:'.72rem',letterSpacing:'2px',color:'#666'}}>VIDEO PLACEHOLDER</p><span style={{fontSize:'.58rem',color:'#444'}}>The lesson video will be added by your instructor.</span></div>;const embed=embedVideoUrl(lesson.playback_url);if(embed)return <div style={videoWrap}><iframe src={embed} title={lesson.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen style={{position:'absolute',inset:0,width:'100%',height:'100%',border:0}}/></div>;return <video key={lesson.id} controls controlsList="nodownload" preload="metadata" src={lesson.playback_url} onTimeUpdate={event=>onProgress(event.currentTarget.currentTime)} style={{width:'100%',maxHeight:'560px',background:'#000',display:'block',marginBottom:'18px'}}/>;}
function embedVideoUrl(raw:string){try{const url=new URL(raw);if(url.hostname.includes('youtube.com')){const id=url.searchParams.get('v')??url.pathname.split('/').filter(Boolean).pop();return id?`https://www.youtube-nocookie.com/embed/${id}`:null;}if(url.hostname==='youtu.be'){const id=url.pathname.slice(1);return id?`https://www.youtube-nocookie.com/embed/${id}`:null;}if(url.hostname.includes('vimeo.com')){const id=url.pathname.split('/').filter(Boolean).pop();return id?`https://player.vimeo.com/video/${id}`:null;}return null;}catch{return null;}}

const page:CSSProperties={minHeight:'100vh',background:'#090909',color:'#fff',fontFamily:'Montserrat,sans-serif'};const topHeader:CSSProperties={height:'82px',padding:'0 22px',display:'flex',alignItems:'center',justifyContent:'space-between',gap:'16px',background:'#0D0D0D',borderBottom:'1px solid rgba(212,175,55,.12)',position:'sticky',top:'72px',zIndex:30};const sidebar:CSSProperties={width:'290px',flexShrink:0,background:'#0D0D0D',borderRight:'1px solid rgba(255,255,255,.06)',display:'flex',flexDirection:'column',maxHeight:'calc(100vh - 154px)',position:'sticky',top:'154px'};const main:CSSProperties={flex:1,minWidth:0,padding:'28px',background:'#090909'};
const center:CSSProperties={minHeight:'60vh',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:'12px'};const progressTrack:CSSProperties={height:'5px',background:'#1C1C1C',overflow:'hidden'};const progressFill:CSSProperties={height:'100%',background:'linear-gradient(90deg,#B8860B,#D4AF37)',transition:'width .4s'};const videoWrap:CSSProperties={position:'relative',paddingTop:'56.25%',background:'#000',marginBottom:'18px'};const videoPlaceholder:CSSProperties={height:'min(420px,42vw)',minHeight:'230px',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',gap:'10px',background:'radial-gradient(circle at center,#171717,#050505)',border:'1px solid rgba(255,255,255,.06)',marginBottom:'18px'};const contentPanel:CSSProperties={background:'#101010',border:'1px solid rgba(255,255,255,.06)',padding:'24px',marginBottom:'18px'};
const navButton:CSSProperties={display:'flex',alignItems:'center',gap:'6px',padding:'9px 13px',background:'#111',border:'1px solid rgba(255,255,255,.09)',color:'#999',fontSize:'.65rem',cursor:'pointer'};const completeButton:CSSProperties={display:'flex',alignItems:'center',gap:'7px',padding:'10px 18px',background:'linear-gradient(135deg,#B8860B,#D4AF37)',border:0,color:'#000',fontFamily:'Cinzel,serif',fontSize:'.65rem',fontWeight:700,cursor:'pointer'};const completeBadge:CSSProperties={display:'flex',alignItems:'center',gap:'5px',fontSize:'.58rem',color:'#34D399',border:'1px solid rgba(52,211,153,.22)',background:'rgba(52,211,153,.07)',padding:'5px 8px'};const mobileButton:CSSProperties={display:'none',width:'34px',height:'34px',placeItems:'center',background:'#111',border:'1px solid rgba(255,255,255,.1)',color:'#D4AF37'};const goldLink:CSSProperties={padding:'10px 16px',background:'linear-gradient(135deg,#B8860B,#D4AF37)',color:'#000',textDecoration:'none',fontFamily:'Cinzel,serif',fontSize:'.65rem',fontWeight:700};
